# Generated by Django 5.0.1 on 2024-01-24 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('typelodgings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='lodgings_images')),
                ('price', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('typelodging', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='typelodgings.typelodging')),
            ],
        ),
    ]
