# Generated by Django 5.0.1 on 2024-01-25 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('lodgings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilodgings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('facilitie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facilities.facilitie')),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lodgings.lodging')),
            ],
        ),
    ]
